rename

diff --git a/.github/workflows/slow_test.yml b/.github/workflows/slow_test.yml
--- a/.github/workflows/slow_test.yml
+++ b/.github/workflows/slow_test.yml
@@ -55,27 +55,27 @@ jobs:
       - name: Start builder container
         if: ${{ !cancelled() && !failure() }}
         run: |
-          BUILDER_CONTAINER=infinity_build_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
+          BUILDER_CONTAINER=hybridsearch_build_$(od -An -N4 -tx4 /dev/urandom | tr -d ' ')
           CPUS=${CPUS:-$(nproc)}
           echo "BUILDER_CONTAINER=${BUILDER_CONTAINER}" >> $GITHUB_ENV
           echo "CPUS=${CPUS}" >> $GITHUB_ENV
           TZ=${TZ:-$(readlink -f /etc/localtime | awk -F '/zoneinfo/' '{print $2}')}
-          sudo docker pull infiniflow/infinity_builder:centos7_clang18
-          sudo docker rm -f -v ${BUILDER_CONTAINER} && sudo docker run --privileged --cap-add=NET_ADMIN -d --name ${BUILDER_CONTAINER} -e TZ=$TZ -e CMAKE_BUILD_PARALLEL_LEVEL=${CPUS} -v $PWD:/infinity -v /boot:/boot -v /var/run/docker.sock:/var/run/docker.sock --cpus ${CPUS} infiniflow/infinity_builder:centos7_clang18
+          sudo docker pull infiniflow/hybridsearch_builder:centos7_clang18
+          sudo docker rm -f -v ${BUILDER_CONTAINER} && sudo docker run --privileged --cap-add=NET_ADMIN -d --name ${BUILDER_CONTAINER} -e TZ=$TZ -e CMAKE_BUILD_PARALLEL_LEVEL=${CPUS} -v $PWD:/hybridsearch -v /boot:/boot -v /var/run/docker.sock:/var/run/docker.sock --cpus ${CPUS} infiniflow/hybridsearch_builder:centos7_clang18
 
       - name: Build release version
         if: ${{ !cancelled() && !failure() }}
-        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /infinity && rm -fr cmake-build-release && mkdir -p cmake-build-release && cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_JOB_POOLS:STRING=link=8 -S /infinity -B /infinity/cmake-build-release && cmake --build /infinity/cmake-build-release --target infinity"
+        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /hybridsearch && rm -fr cmake-build-release && mkdir -p cmake-build-release && cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_JOB_POOLS:STRING=link=8 -S /hybridsearch -B /hybridsearch/cmake-build-release && cmake --build /hybridsearch/cmake-build-release --target hybridsearch"
 
       - name: Install pysdk for Python 3.10
         if: ${{ !cancelled() && !failure() }}
         run: |
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "rm -rf /root/.config/pip/pip.conf && cd /infinity/ && pip3 uninstall -y infinity-sdk && cd python/infinity_sdk/ && pip3 install . -v --config-settings=cmake.build-type='RelWithDebInfo' --config-settings=build-dir='cmake-build-release' -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn && cd ../.."
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "rm -rf /root/.config/pip/pip.conf && cd /infinity/ && pip3 uninstall -y infinity-embedded-sdk && pip3 install . -v --config-settings=cmake.build-type='RelWithDebInfo' --config-settings=build-dir='cmake-build-release' -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn"
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "rm -rf /root/.config/pip/pip.conf && cd /hybridsearch/ && pip3 uninstall -y hybridsearch-sdk && cd python/hybridsearch_sdk/ && pip3 install . -v --config-settings=cmake.build-type='RelWithDebInfo' --config-settings=build-dir='cmake-build-release' -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn && cd ../.."
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "rm -rf /root/.config/pip/pip.conf && cd /hybridsearch/ && pip3 uninstall -y hybridsearch-embedded-sdk && pip3 install . -v --config-settings=cmake.build-type='RelWithDebInfo' --config-settings=build-dir='cmake-build-release' -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn"
 
       - name: Build debug version with thread sanitizer
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_TSAN_TEST == 'true' }}
-        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /infinity && rm -fr cmake-build-debug && mkdir -p cmake-build-debug && cmake -G Ninja -DENABLE_SANITIZER_THREAD=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_JOB_POOLS:STRING=link=8 -S /infinity -B /infinity/cmake-build-debug && cmake --build /infinity/cmake-build-debug --target infinity"
+        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "git config --global safe.directory \"*\" && cd /hybridsearch && rm -fr cmake-build-debug && mkdir -p cmake-build-debug && cmake -G Ninja -DENABLE_SANITIZER_THREAD=ON -DCMAKE_BUILD_TYPE=Debug -DCMAKE_JOB_POOLS:STRING=link=8 -S /hybridsearch -B /hybridsearch/cmake-build-debug && cmake --build /hybridsearch/cmake-build-debug --target hybridsearch"
     
       - name: Prepare restart test data
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_RESTART_TEST == 'true' }}
@@ -88,11 +88,11 @@ jobs:
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_TSAN_TEST == 'true' }}
         id: run_restart_test_sanitizer
         run : |
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn"
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && pip3 install -r python/restart_test/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn"
           # Fix sanitizer: https://github.com/ClickHouse/ClickHouse/issues/64086
           old_value=$(sudo sysctl -n vm.mmap_rnd_bits)
           sudo sysctl -w vm.mmap_rnd_bits=28
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so TSAN_OPTIONS=log_path=restart_tsan.log ASAN_OPTIONS=detect_leaks=0 python3 tools/run_restart_test.py --infinity_path=cmake-build-debug/src/infinity"
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so TSAN_OPTIONS=log_path=restart_tsan.log ASAN_OPTIONS=detect_leaks=0 python3 tools/run_restart_test.py --hybridsearch_path=cmake-build-debug/src/hybridsearch"
           sudo sysctl -w vm.mmap_rnd_bits=$old_value
   
       - name: Collect restart test output with thread sanitizer
@@ -101,7 +101,7 @@ jobs:
           # find all log file like [debug.log.*] in directory, and cat to stdout
         run: |
           failure="${{ steps.run_restart_test_sanitizer.outcome == 'failure'}}"
-          sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure} --tsan_log=restart_tsan.log
+          sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-debug/src/hybridsearch --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure} --tsan_log=restart_tsan.log
           sudo rm restart_tsan.log*
 
       - name: Run cluster test
@@ -111,17 +111,17 @@ jobs:
           # Fix sanitizer: https://github.com/ClickHouse/ClickHouse/issues/64086
           old_value=$(sudo sysctl -n vm.mmap_rnd_bits)
           sudo sysctl -w vm.mmap_rnd_bits=28
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && python3 tools/run_cluster_test.py --infinity_path=cmake-build-debug/src/infinity"
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && rm -fr /var/hybridsearch && python3 tools/run_cluster_test.py --hybridsearch_path=cmake-build-debug/src/hybridsearch"
           sudo sysctl -w vm.mmap_rnd_bits=$old_value
 
       - name: Collect thread sanitizer output in cluster test
         if: ${{ !cancelled() && steps.choose_test_type.outputs.RUN_TSAN_TEST == 'true' }}
         run: |
           failure="${{ steps.run_cluster_test.outcome == 'failure'}}"
-          sudo python3 scripts/collect_cluster_log.py --executable_path=cmake-build-debug/src/infinity --log_dir=/var/infinity/ --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure} --tsan_log=cluster_tsan.log
+          sudo python3 scripts/collect_cluster_log.py --executable_path=cmake-build-debug/src/hybridsearch --log_dir=/var/hybridsearch/ --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure} --tsan_log=cluster_tsan.log
           sudo rm -f cluster_tsan.log*
 
-      - name: Start infinity debug version with thread sanitizer
+      - name: Start hybridsearch debug version with thread sanitizer
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_TSAN_TEST == 'true' }}
         id: start_tests_debug
         run: |
@@ -129,9 +129,9 @@ jobs:
           old_value=$(sudo sysctl -n vm.mmap_rnd_bits)
           echo "old_mmmap_rnd_bits=${old_value}" >> "$GITHUB_OUTPUT"
           sudo sysctl -w vm.mmap_rnd_bits=28
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && TSAN_OPTIONS=log_path=tsan.log cmake-build-debug/src/infinity --config=conf/pytest_parallel_infinity_conf.toml > debug.log 2> debug_error.log &" && sleep 1s
-          if ! sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/infinity > /dev/null; then
-            echo "Failed to start infinity debug version"
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && rm -fr /var/hybridsearch && TSAN_OPTIONS=log_path=tsan.log cmake-build-debug/src/hybridsearch --config=conf/pytest_parallel_hybridsearch_conf.toml > debug.log 2> debug_error.log &" && sleep 1s
+          if ! sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/hybridsearch > /dev/null; then
+            echo "Failed to start hybridsearch debug version"
             cat debug_error.log
             exit 1
           fi
@@ -140,19 +140,19 @@ jobs:
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_TSAN_TEST == 'true' }}
         id: run_tests_debug
         run: |
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so ASAN_OPTIONS=detect_leaks=0 python3 tools/run_pytest_parallel.py" && sleep 1s
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && LD_PRELOAD=/usr/local/lib/clang/18/lib/x86_64-unknown-linux-gnu/libclang_rt.asan.so ASAN_OPTIONS=detect_leaks=0 python3 tools/run_pytest_parallel.py" && sleep 1s
 
-      - name: Stop infinity pysdk & http_api & sqllogictest debug
+      - name: Stop hybridsearch pysdk & http_api & sqllogictest debug
         if: ${{ !cancelled() && steps.choose_test_type.outputs.RUN_TSAN_TEST == 'true' }}
         id: stop_tests_debug
         env:
           old_value: ${{ steps.start_tests_debug.outputs.old_mmmap_rnd_bits }}
         run: |
           sudo chmod +x scripts/timeout_kill.sh
-          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/infinity | xargs echo)
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "/infinity/scripts/timeout_kill.sh 15 ${pids}"
+          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-debug/src/hybridsearch | xargs echo)
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "/hybridsearch/scripts/timeout_kill.sh 15 ${pids}"
           if [ $? -ne 0 ]; then
-              echo "Failed to kill infinity debug version"
+              echo "Failed to kill hybridsearch debug version"
               exit 1
           fi
           sudo sysctl -w vm.mmap_rnd_bits=$old_value
@@ -162,17 +162,17 @@ jobs:
         # GitHub Actions interprets output lines starting with "Error" as error messages, and it automatically sets the step status to failed when such lines are detected.
         run: |
           failure="${{ steps.run_tests_debug.outcome == 'failure' || steps.stop_tests_debug.outcome == 'failure' }}"
-          sudo python3 scripts/collect_log.py --log_path=/var/infinity/log/infinity.log --stdout_path=debug.log --stderror_path=debug_error.log --executable_path=cmake-build-debug/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure} --tsan_log=tsan.log
+          sudo python3 scripts/collect_log.py --log_path=/var/hybridsearch/log/hybridsearch.log --stdout_path=debug.log --stderror_path=debug_error.log --executable_path=cmake-build-debug/src/hybridsearch --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure} --tsan_log=tsan.log
           sudo rm -f tsan.log*
 
       - name: Run restart test
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_RESTART_TEST == 'true' }}
         id: run_restart_test
         run : |
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pip3 install -r python/restart_test/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn"
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && python3 tools/run_restart_test_continuously.py --infinity_path=cmake-build-release/src/infinity"
-        #   sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pytest python/restart_test/test_insert.py -k "test_data[infinity_runner0-columns5-gen-1000000-test/data/config/restart_test/test_insert/1.toml]" -s --infinity_path=cmake-build-release/src/infinity"
-        #   sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && pytest python/restart_test/test_insert.py -k "test_index[infinity_runner0-columns2-indexes2-gen-1000000-test/data/config/restart_test/test_insert/1.toml]" -s --infinity_path=cmake-build-release/src/infinity"
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && pip3 install -r python/restart_test/requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host tuna.tsinghua.edu.cn"
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && python3 tools/run_restart_test_continuously.py --hybridsearch_path=cmake-build-release/src/hybridsearch"
+        #   sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && pytest python/restart_test/test_insert.py -k "test_data[hybridsearch_runner0-columns5-gen-1000000-test/data/config/restart_test/test_insert/1.toml]" -s --hybridsearch_path=cmake-build-release/src/hybridsearch"
+        #   sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && pytest python/restart_test/test_insert.py -k "test_index[hybridsearch_runner0-columns2-indexes2-gen-1000000-test/data/config/restart_test/test_insert/1.toml]" -s --hybridsearch_path=cmake-build-release/src/hybridsearch"
 
       - name: Collect restart test output
         if: ${{ !cancelled() && steps.choose_test_type.outputs.RUN_RESTART_TEST == 'true' }} # always run this step even if previous steps failed
@@ -181,39 +181,39 @@ jobs:
         run: |
           sudo python3 scripts/prepare_restart_test_data.py --op=remove
           failure="${{ steps.run_restart_test.outcome == 'failure'}}"
-          sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-release/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
+          sudo python3 scripts/collect_restart_log.py --executable_path=cmake-build-release/src/hybridsearch --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
 
-      - name: Start infinity release version
+      - name: Start hybridsearch release version
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_PYTEST_PARALLEL == 'true' }}
         # && !contains(github.event.pull_request.labels.*.name, 'invalid')
         run: |
           # Run a command in the background
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && rm -fr /var/infinity && cmake-build-release/src/infinity --config=conf/pytest_parallel_continuous_conf.toml > release.log 2> release_error.log" &
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && rm -fr /var/hybridsearch && cmake-build-release/src/hybridsearch --config=conf/pytest_parallel_continuous_conf.toml > release.log 2> release_error.log" &
 
-      - name: Run pysdk remote infinity & parallel & http_api & sqllogic test release version continously
+      - name: Run pysdk remote hybridsearch & parallel & http_api & sqllogic test release version continously
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_PYTEST_PARALLEL == 'true' }}
         # && !contains(github.event.pull_request.labels.*.name, 'invalid')
         id: run_py_tests
-        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /infinity/ && python3 tools/run_pytest_parallel_continuous.py" && sleep 1s
+        run: sudo docker exec ${BUILDER_CONTAINER} bash -c "cd /hybridsearch/ && python3 tools/run_pytest_parallel_continuous.py" && sleep 1s
 
-      - name: Stop infinity release
+      - name: Stop hybridsearch release
         if: ${{ !cancelled() && !failure() && steps.choose_test_type.outputs.RUN_PYTEST_PARALLEL == 'true' }}
         # && !contains(github.event.pull_request.labels.*.name, 'invalid')
         id: stop_py_tests
         run: |
           sudo chmod +x scripts/timeout_kill.sh
-          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-release/src/infinity | xargs echo)
-          sudo docker exec ${BUILDER_CONTAINER} bash -c "/infinity/scripts/timeout_kill.sh 15 ${pids}"
+          pids=$(sudo docker exec ${BUILDER_CONTAINER} pgrep -f cmake-build-release/src/hybridsearch | xargs echo)
+          sudo docker exec ${BUILDER_CONTAINER} bash -c "/hybridsearch/scripts/timeout_kill.sh 15 ${pids}"
           if [ $? -ne 0 ]; then
-            echo "Failed to kill infinity release version"
+            echo "Failed to kill hybridsearch release version"
             exit 1
           fi
 
-      - name: Collect infinity release output
+      - name: Collect hybridsearch release output
         if: ${{ !cancelled() && steps.choose_test_type.outputs.RUN_PYTEST_PARALLEL == 'true' }} # always run this step even if previous steps failed
         run: |
           failure="${{ steps.run_py_tests.outcome == 'failure' || steps.stop_py_tests.outcome == 'failure' }}"
-          sudo python3 scripts/collect_log.py --log_path=/var/infinity/log/infinity.log --stdout_path=release.log --stderror_path=release_error.log --executable_path=cmake-build-release/src/infinity --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
+          sudo python3 scripts/collect_log.py --log_path=/var/hybridsearch/log/hybridsearch.log --stdout_path=release.log --stderror_path=release_error.log --executable_path=cmake-build-release/src/hybridsearch --output_dir=${RUNNER_WORKSPACE_PREFIX}/log --failure=${failure}
 
       - name: Destroy builder container
         if: always()  # always run this step even if previous steps failed
